# Generated by Django 6.0.3 on 2026-03-29 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogCaterogy',
            new_name='BlogCategory',
        ),
    ]
