# Generated by Django 6.0.3 on 2026-03-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0002_rename_blogcaterogy_blogcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogentry',
            name='category',
        ),
        migrations.AddField(
            model_name='blogentry',
            name='category',
            field=models.ManyToManyField(to='minato.blogcategory'),
        ),
    ]
