# Generated by Django 6.0.3 on 2026-04-18 16:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0003_remove_blogentry_category_blogentry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
