# Generated by Django 6.0.3 on 2026-04-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0004_alter_blogentry_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='body',
            field=models.TextField(),
        ),
    ]
