# Generated by Django 6.0.3 on 2026-05-23 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0005_alter_blogentry_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogentry',
            name='category',
        ),
        migrations.AddField(
            model_name='blogentry',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to='minato.blogcategory'),
            preserve_default=False,
        ),
    ]
