# Generated by Django 6.0.3 on 2026-05-23 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0006_remove_blogentry_category_blogentry_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobTrackerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=50)),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'open'), ('APPLIED', 'applied'), ('REJECTED', 'rejected'), ('OFFER', 'offer'), ('INTERVIEWING', 'interviewing')], default='OPEN', max_length=25)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_name', to='minato.companyname')),
            ],
        ),
    ]
