# Generated by Django 6.0.3 on 2026-05-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0007_companyname_jobtrackerentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtrackerentry',
            name='location',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
