# Generated by Django 6.0.5 on 2026-06-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0008_jobtrackerentry_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('final', 'FINAL')], default='AC', max_length=5),
        ),
    ]
