# Generated by Django 6.0.5 on 2026-06-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0009_blogentry_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTrackerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('started_on', models.DateField()),
                ('status', models.CharField(choices=[('WANT', 'want'), ('READING', 'reading'), ('FINISHED', 'finished'), ('GAVEUP', 'gaveup')], default='OPEN', max_length=25)),
            ],
        ),
    ]
