# Generated by Django 6.0.5 on 2026-06-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0010_booktrackerentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktrackerentry',
            name='ended_on',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
