# Generated by Django 6.0.5 on 2026-06-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0011_booktrackerentry_ended_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktrackerentry',
            name='ended_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booktrackerentry',
            name='started_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
