# Generated by Django 6.0.5 on 2026-06-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0012_alter_booktrackerentry_ended_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email_contact', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
