# Generated by Django 6.0.5 on 2026-07-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0013_guestbookentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktrackerentry',
            name='iken',
            field=models.TextField(default='TEST'),
            preserve_default=False,
        ),
    ]
