# Generated by Django 6.0.5 on 2026-08-05 21:16

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0014_booktrackerentry_iken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='TEXT'),
        ),
    ]
