# Generated by Django 6.0.5 on 2026-09-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0016_xlblogcategory_alter_blogentry_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbookentry',
            name='status',
            field=models.TextField(default='draft'),
            preserve_default=False,
        ),
    ]
