# Generated by Django 6.0.5 on 2026-09-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0017_guestbookentry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbookentry',
            name='website_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
