# Generated by Django 6.0.5 on 2026-09-06 03:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0018_guestbookentry_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbookentry',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
