# Generated by Django 6.0.5 on 2026-09-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0019_guestbookentry_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbookentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('POSTED', 'posted')]),
        ),
    ]
