# Generated by Django 6.0.5 on 2026-09-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0020_alter_guestbookentry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbookentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('POSTED', 'posted')], default='draft'),
        ),
    ]
