# Generated by Django 6.0.5 on 2026-09-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0021_alter_guestbookentry_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watching', models.CharField(max_length=50)),
                ('playing', models.CharField(max_length=50)),
                ('eating', models.CharField(max_length=50)),
                ('listening', models.CharField(max_length=50)),
                ('learning', models.CharField(max_length=50)),
                ('feeling', models.CharField(max_length=50)),
                ('status_message', models.CharField(max_length=200)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
