# Generated by Django 6.0.5 on 2026-09-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0022_singentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singentry',
            name='status_message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
