# Generated by Django 6.0.5 on 2026-09-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0023_alter_singentry_status_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singentry',
            name='status_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
