# Generated by Django 6.0.5 on 2026-09-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0024_alter_singentry_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='singentry',
            name='reading',
            field=models.CharField(default='Eugene Onegin by Pushkin', max_length=50),
            preserve_default=False,
        ),
    ]
