# Generated by Django 6.0.5 on 2026-09-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minato', '0026_bookmarkcategory_bookmarkentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtrackerentry',
            name='company',
        ),
        migrations.AlterField(
            model_name='singentry',
            name='status_message',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.DeleteModel(
            name='CompanyName',
        ),
        migrations.DeleteModel(
            name='JobTrackerEntry',
        ),
    ]
